fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--strict, --scripts-are-modules, --disable-error-code=import-untyped]
